version: "3.9"
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  node:
    restart: always
    build: .
    ports:
      - '81:5000'
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis